language: generic 
sudo: requered
services:
  - docker


before_install:
  - docker build -t johnyabu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true johnyabu/docker-react npm run test -- --coverage 